spring:
  application:
    name: achievements
  config:
    import: optional:configserver:http://localhost:8888

api:
  ninjas:
    key: RcupG1sYqmwHBYHv+tSAog==Swhl0VqPitf41INf
    url: https://api.api-ninjas.com/v1/exercises