spring:
  application:
    name: AchievementApplication

  datasource:
    url: jdbc:mysql://localhost:3306/achievements?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: optional:configserver:http://localhost:8888
