spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: diet-service
          uri: http://localhost:8222
          predicates:
            - Path=/api/v1/diets/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  config:
    import: optional:configserver:http://localhost:8888

# Disable Zipkin tracing
management:
  tracing:
    enabled: false
    sampling:
      probability: 0
    zipkin:
      tracing:
        enabled: false
