eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8073

spring:
  application:
    name: achievements
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/achievements?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Africa/Tunis
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  config:
    auth-url: http://localhost:8090/api/v1/auth
    users-url: http://localhost:8090/api/v1/users
    workouts-url: http://localhost:8074/api/v1/workouts


management:
  tracing:
    sampling:
      probability: 1.0
twilio:
  account:
    sid: ACafeb20f23fbac1262050285872977c84
  auth:
    token: 05f9dd09fa8148b2175ba5414654b767
  phone:
    number: "+18509205916"
