eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/**
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**

        - id: pay
          uri: http://localhost:8090
          predicates:
            - Path=/pay/**
        - id: facilities
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/facilities/**
        - id: buddies
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/buddies/**
        - id: diets
          uri: http://localhost:8072
          predicates:
            - Path=/api/v1/diets/**
        - id: achievements
          uri: http://localhost:8073
          predicates:
            - Path=/api/v1/achievements/**
        - id: challenges
          uri: http://localhost:8073
          predicates:
            - Path=/api/v1/challenges/**
        - id: leaderBoard
          uri: http://localhost:8073
          predicates:
            - Path=/api/v1/leaderBoard/**
        - id: workouts
          uri: http://localhost:8074
          predicates:
            - Path=/api/v1/workouts/**

management:
  tracing:
    sampling:
      probability: 1.0

api:
  security:
    token:
      secret: H4DoS3xt0gQD91lU3iNg1WTx8ab00+LMmh8cQWXekM523vrJu7ZrlAv5M59L3v2qcX5efMK8AXCiMqnQLQyVeA==