eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090

spring:
  application:
    name: users
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
application:
  config:
    achievement-url: http://localhost:8073/api/v1/achievements
    leaderBoard-url: http://localhost:8073/api/v1/leaderBoard
    buddy-url: http://localhost:8071/api/v1/buddies
    workout-url: http://localhost:8074/api/v1/workouts
    facility-url: http://localhost:8070/api/v1/facilities
    diet-url: http://localhost:8072/api/v1/diets
management:
  tracing:
    sampling:
      probability: 1.0

api:
  security:
    token:
      secret: H4DoS3xt0gQD91lU3iNg1WTx8ab00+LMmh8cQWXekM523vrJu7ZrlAv5M59L3v2qcX5efMK8AXCiMqnQLQyVeA==

paypal:
  mode: sandbox
  client:
    id: AeNLyFQhxhKlI03YMTtg4HzuKups6ERg4D-2VLFfKOHGM4VFz-6CNh8rKZSaamkFzN0HriUEbx6XwoaJ
    secret: EBw9uahLHNM-O0ClPalx6m7WJEHXFhPcDoGj6uNyCTq_QNijKM0QjYiAiGWKQHw1SFkLfgoiVuDATalz